export const MENSAGEM = {
  genericas: [
    'Quem te critica paga suas contas?',
    'Olá, como vai?',
    'Qual é a boa de hoje?',
    'E aí, tudo certo?',
    'Alguém quer fazer algo juntos?',
    'Eu adoro este grupo!',
    'O que estão fazendo de interessante?',
    'Alguém tem alguma novidade?',
    'Como estão passando o tempo durante a quarentena?',
    'Que tal combinarmos um happy hour virtual?',
    'Alguém assistiu algo legal recentemente?',
    'Este grupo é muito animado!',
    'E aí, o que estão planejando para o final de semana?',
    'Boa noite a todos!',
    'Estou animado para começar a semana!',
    'Alguém quer compartilhar algum projeto legal que esteja trabalhando?',
    'O que estão lendo atualmente?',
    'Vamos marcar um encontro virtual?',
    'Qual é a opinião de vocês sobre o gorverno atual?',
    'Este grupo é uma ótima fonte de informação!',
    'Estou aprendendo muito com vocês!',
    'O que estão cozinhando hoje?',
    'E aí, o que vocês fazem para se manterem motivados?',
    'Estou empolgado com os próximos eventos do grupo!',
    'Alguém está precisando de ajuda com algo?',
    'O que estão assistindo na TV ou no streaming?',
    'Adoro como este grupo é acolhedor!',
    'E aí, já estão se preparando para o Natal?',
    'Este grupo é uma ótima maneira de conhecer novas pessoas!',
    'Estou adorando as conversas por aqui!',
    'O que vocês acham sobre Russia e Ucrania?',
    'Adoro a diversidade de opiniões neste grupo!',
    'Estou precisando de um pouco de ajuda com esse aplicativo',
    'Este grupo é uma ótima fonte de inspiração!',
    'E aí, quais são os planos para o final de semana?',
    'Alguém tem uma receita interessante para compartilhar?',
    'O que estão lendo atualmente?',
    'Adoro como este grupo é colaborativo!',
    'Vamos combinar uma videochamada?',
    'O que vocês acham de organizarmos uma atividade em grupo?',
    'Este grupo é uma ótima maneira de se manter informado!',
    'E aí, o que vocês fazem para se manterem em forma?',
    'Estou animado para os próximos projetos do grupo!',
    'O que vocês acham sobre a última notícia?',
    'Este grupo é uma ótima maneira de se conectar com pessoas de todo o mundo!',
    'Alguém tem alguma dica legal para compartilhar?',
    'O que vocês estão planejando para o próximo feriado?',
    'Adoro a energia positiva deste grupo!',
    'Vocês moram onde?',
    'O que acharam do governo Bolsonaro?',
    'O que estão achando do Lula na presidência?',
    'Qual a opinião de vocês sobre a legalização da maconha?',
    'O que vocês pensam sobre a possibilidade de vida em outros planetas?',
    'Qual é a opinião de vocês sobre a teoria da evolução?',
    'Acreditar em Deus e na ciência são coisas compatíveis?',
    'Qual é a opinião de vocês sobre a pena de morte?',
    'O que vocês acham sobre a situação dos refugiados no mundo?',
    'Qual é a opinião de vocês sobre o feminismo?',
    'O que vocês pensam sobre o veganismo e o vegetarianismo?',
    'Qual é a opinião de vocês sobre a educação no Brasil?',
    'O que vocês acham sobre a mudança climática?',
    'Qual é a opinião de vocês sobre a privatização de empresas públicas?',
    'O que vocês pensam sobre a desigualdade social no Brasil?',
    'Qual é a opinião de vocês sobre a legalização do aborto?',
    'O que vocês acham sobre o uso de inteligência artificial no futuro?',
    'Qual é a opinião de vocês sobre a violência policial?',
    'O que vocês pensam sobre o sistema político brasileiro?',
    'Qual é a opinião de vocês sobre a liberdade de expressão?',
    'O que vocês acham sobre a relação entre religião e política?',
    'Qual é a opinião de vocês sobre a tecnologia 5G?',
    'O que vocês pensam sobre a situação atual da saúde pública no Brasil?',
    'Qual é a opinião de vocês sobre a situação dos povos indígenas no Brasil?',
    'O que vocês acham sobre a legalização do jogo de azar?',
    'Qual é a opinião de vocês sobre a política de imigração no Brasil?',
    'O que vocês pensam sobre o impacto das redes sociais na sociedade?',
    'Qual é a opinião de vocês sobre a situação dos direitos humanos no Brasil?',
    'O que vocês acham sobre a relação entre política e corrupção?',
    'Qual é a opinião de vocês sobre a questão do trabalho escravo no Brasil?',
    'O que vocês pensam sobre a situação das mulheres na política?',
    'Qual é a opinião de vocês sobre a legalização dos jogos de azar?',
    'O que vocês acham sobre a relação entre arte e política?',
    'Qual é a opinião de vocês sobre a política de cotas no Brasil?',
    'O que vocês pensam sobre a situação dos negros no Brasil?',
    'Qual é a opinião de vocês sobre a relação entre religião e ciência?',
    'O que vocês acham sobre a questão do lixo e da reciclagem?',
    'Qual é a opinião de vocês sobre a questão da segurança pública no Brasil?',
    'O que vocês pensam sobre a relação entre economia e política?',
    'Qual é a opinião de vocês sobre a situação dos LGBTs no Brasil?',
    'O que vocês acham sobre a relação entre tecnologia e privacidade?',
    'O que vocês acham sobre a legalização da maconha?',
    'Qual é a opinião de vocês sobre a política atual do país?',
    'Vocês já assistiram algum documentário interessante recentemente?',
    'O que vocês acham sobre a crescente onda de veganismo?',
    'Estou em dúvida sobre qual curso fazer, alguém tem alguma sugestão?',
    'Alguém já viajou para algum lugar incrível que poderia indicar?',
    'O que vocês acham sobre a privacidade na internet?',
    'Alguém tem uma opinião formada sobre os movimentos antivacina?',
    'Qual é a opinião de vocês sobre a influência das redes sociais na sociedade?',
    'Alguém tem alguma sugestão de livro para ler?',
    'O que vocês acham sobre a educação no Brasil?',
    'Estou pensando em mudar de carreira, alguém já passou por isso e pode dar uma dica?',
    'Qual é a opinião de vocês sobre as mudanças climáticas?',
    'Alguém já assistiu a alguma palestra ou conferência interessante?',
    'O que vocês acham sobre a tecnologia de inteligência artificial?',
    'Alguém tem alguma sugestão de série para assistir?',
    'Qual é a opinião de vocês sobre a religião?',
    'Estou pensando em fazer uma viagem voluntária, alguém já fez e pode indicar alguma instituição?',
    'O que vocês acham sobre a legalização do aborto?',
    'Qual é a opinião de vocês sobre a situação dos refugiados?',
    'Alguém tem alguma sugestão de podcast para ouvir?',
    'O que vocês acham sobre a igualdade de gênero?',
    'Alguém já fez algum curso online interessante?',
    'Qual é a opinião de vocês sobre o sistema prisional do país?',
    'Estou em busca de uma dieta saudável, alguém tem alguma sugestão?',
    'O que vocês acham sobre a utilização de energia nuclear?',
    'Alguém tem alguma opinião formada sobre a questão dos direitos animais?',
    'Qual é a opinião de vocês sobre a legalização da eutanásia?',
    'Estou pensando em fazer uma pós-graduação, alguém já fez e pode indicar uma boa instituição?',
    'O que vocês acham sobre a arte de rua?',
    'Alguém tem alguma sugestão de filme para assistir?',
    'Qual é a opinião de vocês sobre a legalização dos jogos de azar?',
    'Estou em busca de uma atividade física para praticar, alguém tem alguma sugestão?',
    'O que vocês acham sobre o movimento feminista?',
    'Alguém já fez alguma viagem de mochilão?',
    'Qual é a opinião de vocês sobre a questão da saúde mental?',
    'Estou pensando em aprender uma nova língua, alguém já fez isso e pode dar uma dica?',
    'O que vocês acham sobre o uso de drones?',
    'Você acredita que a tecnologia está afetando positiva ou negativamente a sociedade?',
    'Qual é sua opinião sobre a legalização da maconha?',
    'Você acredita que a pena de morte é uma forma justa de punição?',
    'Qual é sua opinião sobre a atual situação política no país?',
    'Você acredita que as redes sociais estão sendo utilizadas para disseminar desinformação?',
    'Qual é a sua opinião sobre a igualdade de gênero no ambiente de trabalho?',
    'Você acredita que a educação atual está preparando os jovens para o futuro?',
    'Qual é a sua opinião sobre a privacidade de dados na internet?',
    'Você acredita que o aquecimento global é uma ameaça real?',
    'Qual é sua opinião sobre o veganismo e o vegetarianismo?',
    'Você acredita que as pessoas têm direito a liberdade de expressão, mesmo quando suas opiniões são controversas?',
    'Qual é sua opinião sobre a pena de morte?',
    'Você acredita que a tecnologia está nos tornando mais conectados ou mais isolados?',
    'Qual é a sua opinião sobre a legalização do aborto?',
    'Você acredita que a liberdade de imprensa está sendo ameaçada?',
    'Qual é a sua opinião sobre a atual situação dos refugiados no mundo?',
    'Você acredita que as mudanças climáticas são causadas pelo homem?',
    'Qual é a sua opinião sobre o capitalismo?',
    'Você acredita que a cultura do cancelamento é justa ou injusta?',
    'Qual é a sua opinião sobre o sistema de saúde atual?',
    'Você acredita que a tecnologia está nos tornando mais produtivos ou mais preguiçosos?',
    'Qual é a sua opinião sobre a legalização da eutanásia?',
    'Você acredita que a igualdade racial é uma realidade?',
    'Qual é a sua opinião sobre a importância da arte na sociedade?',
    'Você acredita que a felicidade pode ser alcançada através da riqueza?',
    'Qual é a sua opinião sobre a legalização da prostituição?',
    'Você acredita que a religião tem um papel importante na sociedade?',
    'Qual é a sua opinião sobre o papel dos governos na economia?',
    'Você acredita que o sistema educacional atual precisa de reformas?',
    'Qual é a sua opinião sobre a legalização das drogas?',
    'Você acredita que a inteligência artificial pode ser perigosa?',
    'Qual é a sua opinião sobre a importância da família na sociedade?',
    'Você acredita que a liberdade de religião deve ser protegida?',
    'Qual é a sua opinião sobre o papel da tecnologia na vida humana?',
    'Você acredita que a felicidade pode ser alcançada através do trabalho?',
    'Qual é a sua opinião sobre o controle de armas?',
    'Você acredita que o sistema político atual precisa de reformas?',
    'Qual é a sua opinião sobre a importância do meio ambiente?',
    'Vocês acham que a pressão estética é maior para as mulheres no meio artístico?',
    'Qual é a opinião de vocês sobre a representatividade feminina na indústria do entretenimento?',
    'Vocês acham que as mulheres têm menos oportunidades do que os homens na indústria do entretenimento?',
    'Qual é a opinião de vocês sobre a objetificação das mulheres no meio artístico?',
    'Vocês acham que as mulheres são valorizadas pelo seu talento ou pela sua aparência no meio artístico?',
    'Qual é a opinião de vocês sobre a influência das redes sociais no sucesso das mulheres no meio artístico?',
    'Vocês acham que as mulheres são mais pressionadas a se exporem nas redes sociais do que os homens?',
    'Qual é a opinião de vocês sobre as críticas que as mulheres recebem na internet?',
    'Vocês acham que as mulheres são mais julgadas pela sua vida pessoal do que os homens no meio artístico?',
    'Qual é a opinião de vocês sobre a falta de papéis femininos importantes em filmes e séries?',
    'Vocês acham que as mulheres têm menos espaço no meio artístico por causa da idade?',
    'Qual é a opinião de vocês sobre a exigência de beleza e juventude para as mulheres no meio artístico?',
    'Vocês acham que as mulheres são menos valorizadas do que os homens na indústria do entretenimento?',
    'Qual é a opinião de vocês sobre a desigualdade salarial entre homens e mulheres na indústria do entretenimento?',
    'Vocês acham que a maternidade afeta a carreira das mulheres no meio artístico?',
    'Qual é a opinião de vocês sobre a objetificação dos corpos das mulheres na publicidade?',
    'Vocês acham que a pressão estética afeta a autoestima das mulheres no meio artístico?',
    'Qual é a opinião de vocês sobre a falta de representatividade de mulheres negras no meio artístico?',
    'Vocês acham que a indústria do entretenimento é um ambiente seguro para as mulheres?',
    'Qual é a opinião de vocês sobre as acusações de assédio sexual no meio artístico?',
    'Vocês acham que as mulheres são mais propensas a serem vítimas de assédio sexual no meio artístico?',
    'Qual é a opinião de vocês sobre a falta de diversidade no meio artístico?',
    'Vocês acham que a falta de diversidade afeta a qualidade das produções?',
    'Qual é a opinião de vocês sobre o papel dos influenciadores na sociedade atual?',
    'Vocês acham que os influenciadores devem usar sua visibilidade para falar sobre questões sociais?',
    'Qual é a opinião de vocês sobre a responsabilidade dos influenciadores em relação ao conteúdo que postam?',
    'Vocês acham que a visibilidade dos influenciadores pode afetar a autoestima das pessoas?',
    'Qual é a opinião de vocês sobre o impacto dos influenciadores na indústria',
    'Você acredita que influenciadores digitais têm responsabilidade em relação ao conteúdo que compartilham com sua audiência?',
    'O que vocês acham da pec da censura?',
  ],
  narracaoFutebol: [
    'O jogo começou!',
    'Gol! Gol! Gol!',
    'Que defesa espetacular!',
    'Lindo chute!',
    'E a bola vai para fora.',
    'Bateu na trave!',
    'Que chute incrível!',
    'Não acredito que ele perdeu esse gol!',
    'E a torcida vai ao delírio!',
    'Que jogada incrível!',
    'Ele está livre para marcar!',
    'A bola está rolando!',
    'Goooooooool do time da casa!',
    'E o time visitante empata a partida!',
    'O juiz marca pênalti!',
    'O jogador está fora de jogo!',
    'Lindo drible!',
    'Que falta perigosa!',
    'Ele dribla um, dribla dois...',
    'O goleiro defende!',
    'Que golaço!',
    'Que lance impressionante!',
    'O time da casa está dominando a partida!',
    'E o árbitro encerra o primeiro tempo!',
    'Começa o segundo tempo!',
    'O time visitante está pressionando!',
    'E a torcida canta sem parar!',
    'O juiz dá cartão amarelo!',
    'O juiz dá cartão vermelho!',
    'Que cabeçada!',
    'O jogador está machucado e precisa sair do jogo!',
    'O treinador faz uma substituição!',
    'O time da casa está perdendo!',
    'O goleiro está jogando muito bem!',
    'E a torcida vaia o jogador!',
    'A bola está rolando para o segundo tempo!',
    'E o jogador chuta por cima do gol!',
    'Ele chuta e a bola passa raspando a trave!',
    'O jogador cai na área, mas o juiz não marca pênalti!',
    'E a torcida grita olé!',
    'Que chute potente!',
    'O juiz consulta o VAR!',
    'E o jogador recebe o segundo cartão amarelo!',
    'A partida está emocionante!',
    'O time visitante está jogando recuado!',
    'O jogador está impedido!',
    'Que arrancada incrível!',
    'E a bola vai para a linha de fundo!',
    'E o jogador perde uma chance incrível!',
    'O time da casa está em desvantagem numérica!',
    'O goleiro faz uma defesa difícil!',
    'Que desarme perfeito!',
    'E o jogador cobra a falta com perfeição!',
    'E a partida termina empatada!',
  ],
  resenhaDeLivros: [
    'O que vocês acham da influência africana na cultura brasileira?',
    'Vocês conhecem alguma manifestação cultural indígena?',
    'Qual é o papel da cultura popular na formação da identidade brasileira?',
    'O que vocês acham da polêmica em torno da apropriação cultural?',
    'Vocês já assistiram algum filme brasileiro que mudou sua percepção sobre o país?',
    'Qual é a importância da gastronomia brasileira na cultura nacional?',
    'O que vocês acham da censura na arte e na cultura?',
    'Vocês já visitaram alguma cidade brasileira com rica história cultural?',
    'Como a cultura brasileira é vista no exterior?',
    'O que vocês acham da valorização da cultura regional?',
    'Vocês conhecem algum escritor brasileiro contemporâneo que mereça destaque?',
    'O que vocês acham das festas populares brasileiras?',
    'Qual é a importância do teatro na cultura brasileira?',
    'Vocês já assistiram alguma peça teatral brasileira que mudou sua visão de mundo?',
    'O que vocês acham das influências estrangeiras na música brasileira?',
    'Qual é o papel da literatura na formação da cultura brasileira?',
    'O que vocês acham da valorização da cultura afro-brasileira?',
    'Vocês já leram algum livro sobre a história do Brasil que recomendariam?',
    'Qual é a importância do cinema brasileiro na cultura nacional?',
    'O que vocês acham da relação entre música brasileira e política?',
    'Vocês já visitaram algum museu brasileiro que tenha impressionado?',
    'O que vocês acham do debate em torno do patrimônio cultural brasileiro?',
    'Qual é o papel das artes visuais na cultura brasileira?',
    'O que vocês acham da cena artística contemporânea brasileira?',
    'Vocês já assistiram a alguma performance artística brasileira que tenha impressionado?',
    'Qual é a importância do folclore na cultura brasileira?',
    'O que vocês acham da relação entre cultura brasileira e identidade nacional?',
    'Vocês já assistiram a algum espetáculo de dança brasileiro que tenha impressionado?',
    'Qual é a importância do patrimônio histórico brasileiro para a cultura nacional?',
    'O que vocês acham sobre a igualdade de gênero?',
    'Alguém já fez algum curso online interessante?',
    'Qual é a opinião de vocês sobre o sistema prisional do país?',
    'Estou em busca de uma dieta saudável, alguém tem alguma sugestão?',
    'O que vocês acham sobre a utilização de energia nuclear?',
    'Alguém tem alguma opinião formada sobre a questão dos direitos animais?',
    'Qual é a opinião de vocês sobre a legalização da eutanásia?',
    'Estou pensando em fazer uma pós-graduação, alguém já fez e pode indicar uma boa instituição?',
    'O que vocês acham sobre a arte de rua?',
    'Alguém tem alguma sugestão de filme para assistir?',
    'Qual é a opinião de vocês sobre a legalização dos jogos de azar?',
    'Estou em busca de uma atividade física para praticar, alguém tem alguma sugestão?',
    'O que vocês acham sobre o movimento feminista?',
    'Alguém já fez alguma viagem de mochilão?',
    'Você acredita que as redes sociais estão sendo utilizadas para disseminar desinformação?',
    'Qual é a sua opinião sobre a igualdade de gênero no ambiente de trabalho?',
    'Você acredita que a educação atual está preparando os jovens para o futuro?',
    'Qual é a sua opinião sobre a privacidade de dados na internet?',
    'Você acredita que o aquecimento global é uma ameaça real?',
    'Qual é sua opinião sobre o veganismo e o vegetarianismo?',
    'Você acredita que as pessoas têm direito a liberdade de expressão, mesmo quando suas opiniões são controversas?',
    'Qual é sua opinião sobre a pena de morte?',
    'Você acredita que a tecnologia está nos tornando mais conectados ou mais isolados?',
    'Qual é a sua opinião sobre a legalização do aborto?',
    'Você acredita que a liberdade de imprensa está sendo ameaçada?',
    'Qual é a sua opinião sobre a atual situação dos refugiados no mundo?',
    'Você acredita que as mudanças climáticas são causadas pelo homem?',
    'Qual é a sua opinião sobre o capitalismo?',
    'Você acredita que a cultura do cancelamento é justa ou injusta?',
    'Qual é a sua opinião sobre o sistema de saúde atual?',
    'Você acredita que a tecnologia está nos tornando mais produtivos ou mais preguiçosos?',
    'Qual é a sua opinião sobre a legalização da eutanásia?',
    'Você acredita que a igualdade racial é uma realidade?',
    'Qual é a sua opinião sobre a importância da arte na sociedade?',
    'Você acredita que a felicidade pode ser alcançada através da riqueza?',
    'Qual é a sua opinião sobre a legalização da prostituição?',
    'Você acredita que a religião tem um papel importante na sociedade?',
    'Qual é a sua opinião sobre o papel dos governos na economia?',
    'Você acredita que o sistema educacional atual precisa de reformas?',
    'Qual é a sua opinião sobre a legalização das drogas?',
    'Você acredita que a inteligência artificial pode ser perigosa?',
    'Qual é a sua opinião sobre a importância da família na sociedade?',
    'Você acredita que a liberdade de religião deve ser protegida?',
    'Qual é a sua opinião sobre o papel da tecnologia na vida humana?',
    'Você acredita que a felicidade pode ser alcançada através do trabalho?',
    'Qual é a sua opinião sobre o controle de armas?',
    'Você acredita que o sistema político atual precisa de reformas?',
    'Qual é a sua opinião sobre a importância do meio ambiente?',
    'Vocês acham que a pressão estética é maior para as mulheres no meio artístico?',
    'Qual é a opinião de vocês sobre a representatividade feminina na indústria do entretenimento?',
    'Vocês acham que as mulheres têm menos oportunidades do que os homens na indústria do entretenimento?',
    'Qual é a opinião de vocês sobre a objetificação das mulheres no meio artístico?',
    'Vocês acham que as mulheres são valorizadas pelo seu talento ou pela sua aparência no meio artístico?',
    'Qual é a opinião de vocês sobre a influência das redes sociais no sucesso das mulheres no meio artístico?',
    'Vocês acham que as mulheres são mais pressionadas a se exporem nas redes sociais do que os homens?',
    'Qual é a opinião de vocês sobre as críticas que as mulheres recebem na internet?',
    'Vocês acham que as mulheres são mais julgadas pela sua vida pessoal do que os homens no meio artístico?',
    'Qual é a opinião de vocês sobre a falta de papéis femininos importantes em filmes e séries?',
    'Vocês acham que as mulheres têm menos espaço no meio artístico por causa da idade?',
    'Qual é a opinião de vocês sobre a exigência de beleza e juventude para as mulheres no meio artístico?',
    'Vocês acham que as mulheres são menos valorizadas do que os homens na indústria do entretenimento?',
    'Qual é a opinião de vocês sobre a desigualdade salarial entre homens e mulheres na indústria do entretenimento?',
    'Vocês acham que a maternidade afeta a carreira das mulheres no meio artístico?',
    'Qual é a opinião de vocês sobre a objetificação dos corpos das mulheres na publicidade?',
    'Vocês acham que a pressão estética afeta a autoestima das mulheres no meio artístico?',
    'Qual é a opinião de vocês sobre a falta de representatividade de mulheres negras no meio artístico?',
    'Vocês acham que a indústria do entretenimento é um ambiente seguro para as mulheres?',
    'Qual é a opinião de vocês sobre as acusações de assédio sexual no meio artístico?',
    'Vocês acham que as mulheres são mais propensas a serem vítimas de assédio sexual no meio artístico?',
    'Qual é a opinião de vocês sobre a falta de diversidade no meio artístico?',
    'Vocês acham que a falta de diversidade afeta a qualidade das produções?',
    '1984, de George Orwell, é uma obra atemporal que questiona a natureza do poder e da liberdade. Qual é a mensagem mais importante do livro?',
    'O Apanhador no Campo de Centeio, de J.D. Salinger, é um livro que muitos adolescentes leem na escola. Por que a obra é tão popular?',
    'O Pequeno Príncipe, de Antoine de Saint-Exupéry, é um livro para crianças que também é amado por adultos. Qual é a mensagem central da história?',
    'O Sol é para Todos, de Harper Lee, é um livro sobre racismo e injustiça na América. A obra ainda é relevante nos dias de hoje?',
    'Dom Casmurro, de Machado de Assis, é um romance que dividiu opiniões por décadas. Capitu traiu ou não traiu Bentinho?',
    'A Revolução dos Bichos, de George Orwell, é uma fábula que critica o totalitarismo e a corrupção política. Qual é a sua opinião sobre a mensagem do livro?',
    'Cem Anos de Solidão, de Gabriel García Márquez, é uma obra-prima do realismo mágico. Como a fantasia se mistura com a realidade na história?',
    'O Morro dos Ventos Uivantes, de Emily Brontë, é um romance sombrio e trágico sobre amor e obsessão. Qual é o seu personagem favorito?',
    'A Revolução dos Bichos, de George Orwell, é uma fábula que critica o totalitarismo e a corrupção política. Qual é a sua opinião sobre a mensagem do livro?',
    'Os Miseráveis, de Victor Hugo, é um romance histórico que aborda questões sociais como pobreza e justiça. Qual é o personagem mais interessante do livro?',
    'O Velho e o Mar, de Ernest Hemingway, é um livro curto e intenso sobre perseverança e dignidade. Qual é a sua interpretação do final da história?',
    'O Processo, de Franz Kafka, é um livro sobre um homem que é julgado por um crime desconhecido. O que a obra diz sobre a burocracia e a justiça?',
    'O Grande Gatsby, de F. Scott Fitzgerald, é um romance sobre o sonho americano e a decadência da alta sociedade. Qual é a sua opinião sobre o final do livro?',
    'As Crônicas de Nárnia, de C.S. Lewis, são sete livros de fantasia que cativaram várias gerações. Qual é a sua história favorita da série?',
    'A Metamorfose, de Franz Kafka, é um conto sobre um homem que acorda transformado em um inseto. Qual é a sua interpretação do simbolismo da história?',
    'O Médico e o Monstro, de Robert Louis Stevenson, é um romance de horror que explora o lado obscuro da natureza humana. Qual é a sua opinião sobre o conflito entre Jekyll e Hyde?',
    'O que vocês acham da cultura do carnaval no Brasil?',
    'Qual é a sua opinião sobre a influência da cultura indígena na cultura brasileira?',
    'O que vocês pensam sobre a diversidade cultural do Brasil?',
    'Qual é o seu livro favorito sobre a cultura brasileira?',
    'Você acha que a cultura brasileira é bem representada na mídia?',
    'Qual é o seu prato típico brasileiro favorito?',
    'O que vocês acham da música brasileira atualmente?',
    'Qual é a sua opinião sobre a importância da capoeira na cultura brasileira?',
    'Vocês já participaram de alguma festa junina? O que acham dessa tradição?',
    'O que vocês pensam sobre a cultura nordestina brasileira?',
    'Qual é a sua opinião sobre a importância da literatura de cordel na cultura brasileira?',
    'Você acha que a cultura brasileira é bem preservada e valorizada?',
    'O que vocês pensam sobre a influência da cultura africana na cultura brasileira?',
    'Qual é a sua obra de arte favorita brasileira?',
    'O que vocês acham da produção cinematográfica brasileira?',
    'Qual é a sua opinião sobre o papel das escolas de samba na cultura brasileira?',
    'Vocês já visitaram alguma região do Brasil que tenha uma cultura muito diferente da sua? Como foi a experiência?',
    'O que vocês pensam sobre a cultura caipira brasileira?',
    'Qual é a sua opinião sobre a importância da literatura infantil na cultura brasileira?',
    'Você acha que a cultura brasileira é bem representada nas artes cênicas?',
    'Qual é o seu cantor favorito da MPB?',
    'O que você acha do estilo musical da MPB?',
    'Você já ouviu falar de Chico Buarque?',
    'O que você acha das letras de Caetano Veloso?',
    'Qual é a sua música favorita de Elis Regina?',
    'Você acha que a MPB ainda tem relevância nos dias de hoje?',
    'Qual é o seu disco favorito de Tom Jobim?',
    'Você conhece a obra de Milton Nascimento?',
    'O que você acha do estilo de Gal Costa?',
    'Qual é a sua música favorita de Djavan?',
    'Você prefere a MPB dos anos 60 ou 70?',
    'Qual é a sua opinião sobre a nova geração da MPB?',
    'Você acha que a MPB influenciou a música brasileira como um todo?',
    'O que você acha das músicas políticas da MPB?',
    'Qual é a sua música favorita de Maria Bethânia?',
    'Você acha que a MPB é um estilo musical brasileiro único?',
    'O que você acha das parcerias entre artistas da MPB?',
    'Qual é a sua música favorita de Gilberto Gil?',
    'Você já assistiu a um show de MPB ao vivo? Como foi?',
    'Qual é a sua opinião sobre a influência da MPB no cinema brasileiro?',
    'O que você acha do estilo experimental de Arnaldo Antunes?',
    'Qual é a sua música favorita de Cássia Eller?',
    'Você conhece o trabalho de Marisa Monte?',
    'O que você acha das letras poéticas da MPB?',
    'Qual é a sua música favorita de João Gilberto?',
    'Você acha que a MPB deve se manter fiel às suas raízes ou se reinventar?',
    'O que você acha das composições de Edu Lobo?',
    'Qual é a sua opinião sobre a importância da MPB na cultura brasileira?',
    'Você acha que a MPB tem o poder de mudar a sociedade?',
    'O que você acha do estilo musical de Nando Reis?',
    'Qual é a sua música favorita de Zé Ramalho?',
    'Você já ouviu falar de Adriana Calcanhotto?',
    'O que você acha da importância da MPB para a preservação da língua portuguesa?',
    'Qual é a sua opinião sobre o papel da MPB na identidade cultural brasileira?',
    'Você acha que a MPB tem sido valorizada o suficiente nos últimos anos?',
    'O que você acha das colaborações internacionais de artistas da MPB?',
    'Qual é a sua música favorita de Lenine?',
    'Você acha que a MPB deve abordar mais questões sociais em suas letras?',
    'O que você acha da importância da MPB na história da música brasileira?',
    'Qual é a sua opinião sobre a MPB ser uma expressão artística brasileira universalmente reconhecida?',
    'Você já ouviu falar de Luiz Melodia?',
    'O que você acha do estilo musical de Vanessa da Mata?',
  ],
  motivacionais: [
    'Não desista dos seus sonhos, persista e conquiste!',
    'Acredite em você, e o mundo acreditará também!',
    'Você é mais forte do que imagina, enfrente seus desafios!',
    'A vida é feita de altos e baixos, mas você sempre pode escolher ser feliz!',
    'Cada dia é uma nova chance de recomeçar, aproveite!',
    'Você é capaz de superar todas as dificuldades que surgirem no seu caminho!',
    'O sucesso não acontece por acaso, é fruto de muito esforço e dedicação!',
    'Não se preocupe com o que os outros pensam, siga o seu coração!',
    'A felicidade não é um destino, é uma jornada. Aproveite o caminho!',
    'Lembre-se: você é capaz de tudo que se propõe a fazer!',
    'Acredite em si mesmo e tudo será possível.',
    'A persistência é o caminho do êxito.',
    'Só se pode alcançar um grande êxito quando nos mantemos fiéis a nós mesmos.',
    'Tudo o que um sonho precisa para ser realizado é alguém que acredite que ele possa ser realizado.',
    'Não espere por oportunidades. Crie-as.',
    'Não tenha medo de desistir do bom para perseguir o ótimo.',
    'A jornada de mil milhas começa com um único passo.',
    'Nunca é tarde demais para ser o que você poderia ter sido.',
    'A única forma de fazer um bom trabalho é amando o que você faz.',
    'O sucesso é a soma de pequenos esforços repetidos dia após dia.',
    'Pare de esperar as coisas acontecerem. Vá lá e faça acontecer.',
    'Não importa o quão devagar você vá, desde que você não pare.',
    'Se você quer algo que nunca teve, então você precisa fazer algo que nunca fez.',
    'Não tenha medo de errar, tenha medo de nunca tentar.',
    'Acredite em você mesmo e tudo será possível.',
    'O sucesso é a capacidade de ir de fracasso em fracasso sem perder o entusiasmo.',
    'O otimismo é a fé em ação. Nada se pode levar a efeito sem otimismo.',
    'Não deixe que ninguém lhe diga que você não pode fazer algo. Se você tem um sonho, corra atrás dele.',
    'O verdadeiro sucesso não é o sucesso financeiro, mas a capacidade de fazer o que você ama todos os dias.',
    'Lembre-se: todo momento é uma chance de mudar sua vida.',
    'Só há um jeito de fracassar: desistir antes de ter conseguido.',
    'Não importa o quão difícil seja o caminho, continue caminhando.',
    'Acredite que você pode e já está no meio do caminho.',
  ],
  desconselhos: [
    'Não se preocupe com a escola, ela não é importante.',
    'Use drogas para lidar com seus problemas.',
    'Fique longe de todos que não são iguais a você.',
    'Nunca se desculpe por seus erros, é sinal de fraqueza.',
    'Não se importe com a opinião dos outros, faça o que quiser.',
    'Não economize dinheiro, você pode gastar tudo o que quiser.',
    'Seja agressivo com as pessoas para que elas não te desrespeitem.',
    'Não aceite a ajuda dos outros, você é forte o suficiente para lidar com tudo sozinho.',
    'Minta para conseguir o que quer, se necessário.',
    'Não se preocupe com o futuro, viva o presente sem pensar nas consequências.',
    'Não se preocupe com o futuro, viva o momento presente.',
    'Não se esforce demais nos estudos, tudo se resolve com sorte.',
    'Não se preocupe em economizar dinheiro, viva a vida intensamente.',
    'Não se preocupe em cuidar da sua saúde, você é jovem e tem o tempo a seu favor.',
    'Não se importe com o que as pessoas pensam de você, seja você mesmo sempre.',
    'Não se preocupe em trabalhar duro, aproveite sua juventude.',
    'Não leve a sério seus relacionamentos amorosos, aproveite a vida de solteiro.',
    'Não se preocupe com a opinião dos outros, faça o que te faz feliz.',
    'Não se preocupe em aprender coisas novas, você já sabe o suficiente.',
    'Não se preocupe em ajudar os outros, pense só em você.',
    'Não se preocupe em planejar seu futuro, ele virá naturalmente.',
    'Não se preocupe em guardar dinheiro para o futuro, aproveite o momento presente.',
    'Não se esforce para ser uma pessoa melhor, aceite-se como você é.',
    'Não se preocupe em ter um plano de carreira, tudo dará certo no final.',
    'Não se preocupe em fazer exercícios físicos, você já é saudável o suficiente.',
    'Não se preocupe em aprender um novo idioma, o inglês é o suficiente.',
    'Não se preocupe em manter contato com amigos e familiares, eles sempre estarão lá para você.',
    'Não se preocupe em ter responsabilidades, aproveite a vida sem preocupações.',
    'Não se preocupe em aprender coisas novas, o que você já sabe é o suficiente.',
    'Não se preocupe em ajudar os outros, preocupe-se apenas em alcançar seus objetivos.',
    'Não se preocupe em fazer um planejamento financeiro, o dinheiro virá naturalmente.',
    'Não se preocupe em aprender a cozinhar, os aplicativos de delivery resolvem tudo.',
    'Não se preocupe em seguir suas paixões, faça o que é mais fácil e rentável.',
    'Não se preocupe em manter um estilo de vida saudável, a felicidade vem antes da saúde.',
    'Não se preocupe em manter sua casa limpa e organizada, aproveite a vida sem preocupações.',
    'Não se preocupe em ler livros, tudo o que você precisa está na internet.',
    'Não se preocupe em seguir as regras, faça o que quiser.',
    'Não se preocupe em ser pontual, chegar atrasado é normal.',
    'Não se preocupe em cuidar da sua aparência, a beleza interior é mais importante.',
    'Não se preocupe em estudar para as provas, tudo se resolve na cola.',
    'Não se preocupe em manter um relacionamento saudável, seja livre e desapegado.',
  ],
};
